imports

In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#now from sklearn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import Ridge, LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, precision_score, accuracy_score, recall_score

loading and checking data

In [95]:
df = pd.read_csv("Social_Network_Ads.csv")
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [96]:
#as user id is useless we dropping it
# df = df.drop('User ID', axis=1)
df = df.drop(columns=['User ID'])
df

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0
...,...,...,...,...
395,Female,46,41000,1
396,Male,51,23000,1
397,Female,50,20000,1
398,Male,36,33000,0


In [97]:
# #removing the outliers
# df = df[(df['Age'] < df['Age'].quantile(0.95)) & (df['Age'] > df['Age'].quantile(0.05))]
# df = df[(df['EstimatedSalary'] < df['EstimatedSalary'].quantile(0.95)) & (df['EstimatedSalary'] > df['EstimatedSalary'].quantile(0.05))]

In [98]:
#encoding categorical
categorical_features = ['Gender']
label_encoder = LabelEncoder()

for col in categorical_features:
    df[col] = label_encoder.fit_transform(df[col])

df


,Gender,Age,EstimatedSalary,Purchased
2,0,26,43000,0
3,0,27,57000,0
5,1,27,58000,0
6,0,27,84000,0
8,1,25,33000,0
...,...,...,...,...
394,0,39,59000,0
395,0,46,41000,1
396,1,51,23000,1
398,1,36,33000,0


In [99]:
#splitting into features and target i.e X and y
X = df.drop(columns=['Purchased'])
y = df['Purchased']
X


,Gender,Age,EstimatedSalary
2,0,26,43000
3,0,27,57000
5,1,27,58000
6,0,27,84000
8,1,25,33000
...,...,...,...
394,0,39,59000
395,0,46,41000
396,1,51,23000
398,1,36,33000


In [100]:
#standardising the features in X i.e scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)
X


array([[-9.78425814e-01, -1.37196318e+00, -9.01561770e-01],
       [-9.78425814e-01, -1.25539352e+00, -4.16396090e-01],
       [ 1.02204989e+00, -1.25539352e+00, -3.81741399e-01],
       [-9.78425814e-01, -1.25539352e+00,  5.19280579e-01],
       [ 1.02204989e+00, -1.48853284e+00, -1.24810868e+00],
       [-9.78425814e-01, -3.22836228e-01, -1.39158558e-01],
       [-9.78425814e-01, -1.37196318e+00,  3.80661813e-01],
       [-9.78425814e-01, -1.37196318e+00, -5.89669547e-01],
       [ 1.02204989e+00, -1.02225420e+00,  3.80661813e-01],
       [ 1.02204989e+00,  1.07599971e+00, -1.52534622e+00],
       [ 1.02204989e+00,  8.42860387e-01, -1.49069152e+00],
       [ 1.02204989e+00,  9.59430049e-01, -1.42138214e+00],
       [-9.78425814e-01,  1.19256937e+00, -1.38672745e+00],
       [ 1.02204989e+00,  8.42860387e-01, -1.62931029e+00],
       [-9.78425814e-01,  1.07599971e+00, -6.93633622e-01],
       [ 1.02204989e+00,  1.19256937e+00, -9.70871153e-01],
       [-9.78425814e-01,  8.42860387e-01

In [101]:
#split into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [102]:
#logistic regression to check if they bought it or not
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [103]:
#ridge regression to check same
ridge_regression = Ridge()
ridge_regression.fit(X_train, y_train)

,alpha,1.0
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [104]:
#evaluate models
y_pred_logistic = logistic_regression.predict(X_test)
y_pred_ridge = ridge_regression.predict(X_test)
y_pred_ridge

array([ 0.27943068,  0.41076562,  0.6396805 ,  0.49223754,  0.18290149,
        0.35201201,  0.22376041,  0.62116158,  0.7882377 ,  0.40792819,
        0.90445007,  0.24431282,  0.85224054,  0.32880278,  0.65214626,
        0.31115309,  0.19043103,  0.22604072,  0.12180228,  0.24400161,
        0.26949115,  0.39984154, -0.13007501,  0.47686816,  0.39903851,
        0.30541294,  0.10377608,  0.01799036,  0.27578932,  0.40169532,
        0.00181795,  0.35589928, -0.12248108,  0.40299108,  0.42088668,
        0.22579481,  0.74503318, -0.0036119 ,  0.11711107,  0.76607832,
        0.42064077, -0.19561953,  0.89352599,  0.34805944,  0.025519  ,
        0.62301536,  0.39305154,  0.34861656,  0.40218804, -0.07829201,
        0.31189173, -0.08662458,  0.57049372,  0.09211336,  0.87643432,
        0.35954064,  0.55284494,  0.0613755 ,  0.63733399,  0.37620578,
        0.21487072,  0.34392535,  0.44045454,  0.48464271,  0.22085769])

In [105]:
import numpy as np

# Convert continuous predictions to binary class labels (e.g., 0 or 1)
y_pred_ridge_class = np.where(y_pred_ridge >= 0.5, 1, 0)
y_pred_ridge_class

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [106]:
#accuracy
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

accuracy_ridge = accuracy_score(y_test, y_pred_ridge_class)

print(f"Logistic Regression Accuracy: {accuracy_logistic}\nRidge Regression Accuracy: {accuracy_ridge}")

Logistic Regression Accuracy: 0.9076923076923077
Ridge Regression Accuracy: 0.8923076923076924


In [107]:
#precision

precision_logistic = precision_score(y_test, y_pred_logistic)
precision_ridge = precision_score(y_test, y_pred_ridge_class)

print(f"Logistic Regression Precision: {precision_logistic}\nRidge Regression Precision: {precision_ridge}")

Logistic Regression Precision: 0.8
Ridge Regression Precision: 0.7857142857142857


In [108]:
#confusion matrix
cm_logistic = confusion_matrix(y_test, y_pred_logistic)
cm_ridge = confusion_matrix(y_test, y_pred_ridge_class)

print(f"Logistic Regression Confusion Matrix:\n{cm_logistic}")
print(f"Ridge Confusion Matrix:\n{cm_ridge}")

Logistic Regression Confusion Matrix:
[[47  3]
 [ 3 12]]
Ridge Confusion Matrix:
[[47  3]
 [ 4 11]]


In [109]:
#classification report
cr_logistic = classification_report(y_test, y_pred_logistic)
cr_ridge = classification_report(y_test, y_pred_ridge_class)

print(f"Logistic Regression Classification Report:\n{cr_logistic}")
print(f"Ridge Classification Report:\n{cr_ridge}")

Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        50
           1       0.80      0.80      0.80        15

    accuracy                           0.91        65
   macro avg       0.87      0.87      0.87        65
weighted avg       0.91      0.91      0.91        65

Ridge Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93        50
           1       0.79      0.73      0.76        15

    accuracy                           0.89        65
   macro avg       0.85      0.84      0.84        65
weighted avg       0.89      0.89      0.89        65



In [110]:
recall_logistic = recall_score(y_test, y_pred_logistic)
recall_ridge = recall_score(y_test, y_pred_ridge_class)

print(f'recall_logistic: {recall_logistic}\nrecall_ridge: {recall_ridge}')

recall_logistic: 0.8
recall_ridge: 0.7333333333333333


In [114]:
#tuning logistic model
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}
grid_search = GridSearchCV(estimator=logistic_regression, param_grid=param_grid, cv=5, scoring='f1')
grid_search.fit(X_train, y_train)

grid_search.best_params_

best_model = grid_search.best_estimator_
y_pred_tunedLogi = best_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_tunedLogi)
cm_ridge = confusion_matrix(y_test, y_pred_ridge_class)

print(f"Tuned Logistic Regression Confusion Matrix:\n{cm_ridge}")

print(f"Tuned Classification Report:\n{cm_ridge}")



Tuned Logistic Regression Confusion Matrix:
[[47  3]
 [ 4 11]]
Tuned Classification Report:
[[47  3]
 [ 4 11]]


this is the part where mam added the code for thhe predictjor fuction which ill see and try. Also no benefit of tuning

In [ ]:
# # Function to predict based on user input
# def predict_purchase():
#     print("Enter the following details to predict purchase:")
#
#     # Getting user input
#     gender = input("Gender (Male/Female): ").strip().capitalize()
#     age = int(input("Age (in years): ").strip())
#     salary = int(input("Estimated Salary (in USD): ").strip())
#
#     # Encoding and scaling the input
#     gender_encoded = 1 if gender == "Male" else 0
#     input_features = [[gender_encoded, age, salary]]
#     input_scaled =
# # Encoding and scaling the input
#     gender_encoded = 1 if gender == "Male" else 0
#     input_features = [[gender_encoded, age, salary]]
#     input_scaled = scaler.transform(input_features)
#
#     # Making a prediction
#     prediction = log_reg.predict(input_scaled)
#     probability = log_reg.predict_proba(input_scaled)
#
#     # Outputting the result
#     result = "Purchase" if prediction[0] == 1 else "No Purchase"
#     print(f"\nPrediction: {result}")
#     print(f"Probability of 'No Purchase': {pr
# print(f"Probability of 'No Purchase': {probability[0][0]:.2f}")
#     print(f"Probability of 'Purchase': {probability[0][1]:.2f}")
#
# # Call the prediction function
# predict_purchase()
#
#
# # Evaluating the model
# accuracy = accuracy_score(y_test, y_pred)
# conf_matrix = confusion_matrix(y_test, y_pred)
# class_report = classification_report(y_test, y_pred)
#
# # Printing the evaluation results
# print("Model Accuracy: {:.2f}%".format(accuracy * 100))
# print("\nConfusion Matrix:\n", conf_matrix)
# print("\nClassific
# Techvanto Academy
# 16:59
# # Printing the evaluation results
# print("Model Accuracy: {:.2f}%".format(accuracy * 100))
# print("\nConfusion Matrix:\n", conf_matrix)
# print("\nClassification Report:\n", class_report)
#
# # Comparing predictions with actual data
# comparison_df = pd.DataFrame({
#     "Actual": y_test.values,
#     "Predicted": y_pred
# })
#
# # Displaying the comparison
# print("\nComparison of Actual vs Predicted values:")
# print(comparison_df.head())